series: Basic C++
title: Structs and Classes
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Structs and classes help manage smaller pieces of your program.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: Headers